SELECT
    idnum,
    yyyymm,
    request_date,
    id,
    request_type,
    request_subtype,
    oper,
    oper_g,
    operation_date,
    ticket_begdate,
    ticket_enddate,
    ticket_ser,
    ticket_num,
    train_category,
    train_num,
    agent_code,
    carriage_code,
    paymenttype,
    sale_station,
    region_code,
    payagent_id,
    web_id,
    departure_station,
    arrival_station,
    pass_qty,
    abonement_type,
    abonement_subtype,
    carryon_type,
    carryon_weight,
    seatstick_limit,
    carriage_class,
    benefit_region,
    benefit_code,
    benefitgroup_code,
    fee_sum,
    refundfee_sum,
    total_sum,
    tariff_sum,
    refund_sum,
    department_sum,
    refunddepart_sum,
    no_use,
    server_datetime,
    server_reqnum


FROM zzz_rawdl2.l2_prig_main
WHERE request_date = ${requestDate}
ORDER BY idnum